[package]
name = "lox_interpreter_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lox_parser = { path = "../lox_parser" }
lox_interpreter = { path = "../lox_interpreter" }
