[workspace]
resolver = "2"
members = [
    "lox_ast",
    "lox_bytecode_ops",
    "lox_bytecode",
    "lox_interpreter_cli",
    "lox_interpreter",
    "lox_lexer",
    "lox_macros",
    "lox_parser",
    "lox_resolver",
    "lox_vm_cli",
]
