[package]
name = "lox_bytecode_ops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "2.2.6"
lox_ast = { path = "../lox_ast" }
lox_macros = { path = "../lox_macros" }
thiserror = "1.0.57"
